/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ImportPaperRouteImport } from './routes/import-paper'
import { Route as HomeRouteImport } from './routes/home'
import { Route as E2eRouteImport } from './routes/e2e'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntriesNewRouteImport } from './routes/entries.new'
import { Route as EntriesIdRouteImport } from './routes/entries.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportPaperRoute = ImportPaperRouteImport.update({
  id: '/import-paper',
  path: '/import-paper',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eRoute = E2eRouteImport.update({
  id: '/e2e',
  path: '/e2e',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesNewRoute = EntriesNewRouteImport.update({
  id: '/entries/new',
  path: '/entries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntriesIdRoute = EntriesIdRouteImport.update({
  id: '/entries/$id',
  path: '/entries/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/coverage': typeof CoverageRoute
  '/e2e': typeof E2eRoute
  '/home': typeof HomeRoute
  '/import-paper': typeof ImportPaperRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/coverage': typeof CoverageRoute
  '/e2e': typeof E2eRoute
  '/home': typeof HomeRoute
  '/import-paper': typeof ImportPaperRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/coverage': typeof CoverageRoute
  '/e2e': typeof E2eRoute
  '/home': typeof HomeRoute
  '/import-paper': typeof ImportPaperRoute
  '/logs': typeof LogsRoute
  '/settings': typeof SettingsRoute
  '/entries/$id': typeof EntriesIdRoute
  '/entries/new': typeof EntriesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacts'
    | '/coverage'
    | '/e2e'
    | '/home'
    | '/import-paper'
    | '/logs'
    | '/settings'
    | '/entries/$id'
    | '/entries/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/coverage'
    | '/e2e'
    | '/home'
    | '/import-paper'
    | '/logs'
    | '/settings'
    | '/entries/$id'
    | '/entries/new'
  id:
    | '__root__'
    | '/'
    | '/contacts'
    | '/coverage'
    | '/e2e'
    | '/home'
    | '/import-paper'
    | '/logs'
    | '/settings'
    | '/entries/$id'
    | '/entries/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactsRoute: typeof ContactsRoute
  CoverageRoute: typeof CoverageRoute
  E2eRoute: typeof E2eRoute
  HomeRoute: typeof HomeRoute
  ImportPaperRoute: typeof ImportPaperRoute
  LogsRoute: typeof LogsRoute
  SettingsRoute: typeof SettingsRoute
  EntriesIdRoute: typeof EntriesIdRoute
  EntriesNewRoute: typeof EntriesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-paper': {
      id: '/import-paper'
      path: '/import-paper'
      fullPath: '/import-paper'
      preLoaderRoute: typeof ImportPaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e': {
      id: '/e2e'
      path: '/e2e'
      fullPath: '/e2e'
      preLoaderRoute: typeof E2eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/new': {
      id: '/entries/new'
      path: '/entries/new'
      fullPath: '/entries/new'
      preLoaderRoute: typeof EntriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entries/$id': {
      id: '/entries/$id'
      path: '/entries/$id'
      fullPath: '/entries/$id'
      preLoaderRoute: typeof EntriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactsRoute: ContactsRoute,
  CoverageRoute: CoverageRoute,
  E2eRoute: E2eRoute,
  HomeRoute: HomeRoute,
  ImportPaperRoute: ImportPaperRoute,
  LogsRoute: LogsRoute,
  SettingsRoute: SettingsRoute,
  EntriesIdRoute: EntriesIdRoute,
  EntriesNewRoute: EntriesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
